spring:
  application:
    name: be-full-text-search
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poetry?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  elasticsearch:
    username: elastic
    password: akq2bwUUZu+4s=GuxdXA
