spring:
  application:
    name: be-full-text-search
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    poetry:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3316/poetry?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    novel:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3316/novel?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
  elasticsearch:
    username: elastic
    password: akq2bwUUZu+4s=GuxdXA
